name: TeammingSlots
version: '${version}'
main: srdqrk.teammingslots.TeammingSlots
api-version: 1.19
permissions:
  teammingslots.executer:
    description: Permiso para ejecutar comandos. Permiso solo para staffs
    default: false